### ISSUE TITLE
Inquiry Regarding Data Generation Details

### ISSUE THREAD

**Issue by JoeSandos** [xianggebenben/IVGD#1]
I am particularly interested in the technical details of the data generation.  

What concerns me is that according to my research, most current papers regarding source localization do not contain the settings of the simulation (e.g. the choice of infection probability/recovery probability in SIR; are they heterogeneous, or all the edges share the same prob;) for the cascade generation in datasets used as basement in training and testing.

 I am particularly interested in the technical details of the data simulation. Could you kindly share the relevant codes or information about the choice of specific parameters that may help me understand the process of data generation?

**Comment by xianggebenben** [comment]
Hi, Thank you for your interest in our paper. We used the IC model in our simulation. The infection probability was 0.1. All the edges shared different probabilities. But they are uniformly distributed between 0 and 0.15. Please let me know if you have any questions.

**Comment by JoeSandos** [comment]
Thank you. However, I noticed that in your dataset provided in the codes, continuous numbers are included in the _influ_mat_list_ variable instead of discrete labels {0,1} indicating whether the node is infected or not. The meaning of the continuous vector does not seem to be mentioned in the paper. Could you please provide me with the relevant code for the data generation?
