### ISSUE TITLE
diffusion processing

### ISSUE THREAD

**Issue by xxTangg** [xianggebenben/IVGD#2]
This algorithm is based on the fact that the source detection is found in the case of the scattered model. So when comparing the experiment, is other models also using graph residual networks to disseminate simulation? But I see that the pre -training diagram diffusion model in your code uses MLP for training, so I don't understand this place very well.

**Comment by xianggebenben** [comment]
Thanks for your interest in our paper. It is unclear what the meaning of other models is here.  If they mean comparison methods, then they DO NOT use graph residual networks to disseminate simulation. If  they mean other diffusion models, then they can use the graph residual networks. The MLP is diffusion model of the deepIS model, but it can be replaced with other diffusion models as well. Hope this helps.

**Comment by xxTangg** [comment]
Sorry, maybe my previous statement was not very clear. What I mean is as follows: So the diffusion dynamics model of the IVGD algorithm uses the IC model, and then the reversible graph residual network is only used for feature construction and uses the reversible characteristics for source point estimation? In the algorithm comparison section, are the diffusion dynamics models of other algorithms also using the IC model?

**Comment by xianggebenben** [comment]
Thanks for clarification. 
1.  A typical graph diffusion model consists of  feature construction and label propagation. The feature construction is the MLP module to encode node embeddings, and the label propgation is to use the underlying diffusion model for graph diffsion (e.g. IC or LT model). The reversible graph residual network is used on both feature construction and label propogation for source prediction.
2.  For the performance evaluation, comparison methods do not have assumption on the underlying diffusion model such as LPSI. So they do not need to specify the diffusion models.

**Comment by xxTangg** [comment]
Thank you for your answer. Regarding the second point: In terms of comparison experiments, isn't the data set only about nodes and associations? What dynamic model is used to simulate information diffusion for source point detection? Or is the dynamic model of data generation inconsistent when comparing experiments? Looking forward to your answer!




---Original---
From: "Junxiang ***@***.***&gt;
Date: Tue, Nov 21, 2023 23:53 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [xianggebenben/IVGD] diffusion processing (Issue #2)




 
Thanks for clarification.
  
A typical graph diffusion model consists of  feature construction and label propagation. The feature construction is the MLP module to encode node embeddings, and the label propgation is to use the underlying diffusion model for graph diffsion (e.g. IC or LT model). The reversible graph residual network is used on both feature construction and label propogation for source prediction.
 
For the performance evaluation, comparison methods do not have assumption on the underlying diffusion model such as LPSI. So they do not need to specify the dffusion models.

**Comment by xianggebenben** [comment]
The data is the graph topology and labels of all nodes. We used the IC model to simulate graph diffusion. Thanks.

**Comment by xxTangg** [comment]
Thank you for your patience! All the best



---Original---
From: "Junxiang ***@***.***&gt;
Date: Wed, Nov 22, 2023 00:19 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [xianggebenben/IVGD] diffusion processing (Issue #2)




 
The data is the graph topology and labels of all nodes. We used the IC model to simulate graph diffusion. Thanks.
