### ISSUE TITLE
Question about dataset generation (prob_matrix)

### ISSUE THREAD

**Issue by MrYansong** [xianggebenben/IVGD#3]
Hello, IVGD is a great work. I'm presently engaged in relevant research and aim to leverage IVGD as a robust benchmark. Nevertheless, it appears that the 'prob_matrix' within the dataset lacks a clear definition. Could you kindly provide insight into its calculation methodology?
Thanks in advance! Looking forward to hearing from you.

**Comment by xianggebenben** [comment]
> Hello, IVGD is a great work. I'm presently engaged in relevant research and aim to leverage IVGD as a robust benchmark. Nevertheless, it appears that the 'prob_matrix' within the dataset lacks a clear definition. Could you kindly provide insight into its calculation methodology? Thanks in advance! Looking forward to hearing from you.

Thank you for the interest in our work.  The prob_matrix within the dataset refers to the code from DeepIS: https://github.com/xiawenwen49/DeepIS/blob/master/data/prepare_dataset.py. Hope this helps.

Best

**Comment by MrYansong** [comment]
Thank you for your reply!
